###############################
# docker-compose.yml
###############################
version: '3.9'
services:
  # Sandbox environment for development 
  # and network connection to local blockchain node 
  app:
    image: ghcr.io/chrisnft/sandbox:latest
    container_name: playground-client
    working_dir: /home/sandbox/playground
    stdin_open: true
    tty: true

volumes:
  playground:
